### PR TITLE
Update version of node needed

### LINKED ISSUE #28: Running 'yarn build' fails with TypeScript error
# Summary
Running `yarn build` fails.

MacOS: `10.15.5`
Node: `12.18.1`
Typescript: `2.7.9`

WIth the output: 

```
src/ecc/keys.ts:27:10 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(format: "jwk", keyData: JsonWebKey, algorithm: string | Algorithm | AesKeyAlgorithm | EcKeyImportParams | HmacImportParams | RsaHashedImportParams | DhImportKeyParams, extractable: boolean, keyUsages: KeyUsage[]): PromiseLike<...>', gave the following error.
    Argument of type '"raw"' is not assignable to parameter of type '"jwk"'.
  Overload 2 of 3, '(format: "raw" | "pkcs8" | "spki", keyData: ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | ... 5 more ... | Float64Array, algorithm: string | ... 5 more ... | DhImportKeyParams, extractable: boolean, keyUsages: KeyUsage[]): PromiseLike<...>', gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type 'KeyUsage[]'.
  Overload 3 of 3, '(format: string, keyData: ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | ... 5 more ... | JsonWebKey, algorithm: string | ... 5 more ... | DhImportKeyParams, extractable: boolean, keyUsages: KeyUsage[]): PromiseLike<...>', gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type 'KeyUsage[]'.

 27   return window.crypto.subtle.importKey(
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 28     'raw',
    ~~~~~~~~~~
... 
 32     uses
    ~~~~~~~~
 33   )
    ~~~
```

### PR DESCRIPTION
**Pull request by bmann**
Looking to fix #28 

Picked this version from the types/node line as a total guess :)

### CODE REVIEW

**Comment by icidasset** [comment]
Can you do a `yarn install` Boris?
Also, I would not use the `^` prefix here for the version number.
Rather do something like `>=13.7.0`

**Comment by dholms** [comment]
Seems to build fine on as early as Node v10 :thinking: 
https://travis-ci.org/github/fission-suite/keystore-idb/builds/709731294

**Comment by dholms** [comment]
I'm fine with bumping up the version to `node >= v10.21.0` since that's what we test in Travis. We can even go higher and remove the nodev10 travis build if we want. But I don't think that this is the issue. it seems to be an issue with a later version of the typescript compiler

**Comment by bmann** [comment]
Yes we should align this version with what we are doing in CI — because then we’ll know if it doesn’t work!

I’d have to go look at node LTS strategies to actually pick a number. Let’s go with the 10 for now.

**Comment by dholms** [comment]
Closing in lieu of https://github.com/fission-suite/keystore-idb/pull/31

**Pull request closed without merging**
